### ISSUE TITLE
z = torch.randn(FLAGS.batch_size * 2, FLAGS.z_dim).to(device)

### ISSUE THREAD

**Issue by sumorday** [w86763777/pytorch-gan-collections#13]
why generator batch_size will multiply two？
Thank you！！

**Comment by w86763777** [comment]
This follows the official [implementation](https://github.com/pfnet-research/sngan_projection/blob/master/configs/sn_cifar10_unconditional.yml#L45).
As far as I understand, the total batch size of discriminator is also `2 * batch_size` which includes fake and real images.

**Comment by sumorday** [comment]
Thank you sooooooo much!! You are the best!
