### ISSUE TITLE
Unable to allocate 2.57 GiB for an array with shape (2764800000,) and data type uint8

### ISSUE THREAD

**Issue by sumorday** [w86763777/pytorch-gan-collections#16]
everything = np.fromfile(f, dtype=np.uint8)
numpy.core._exceptions.MemoryError: Unable to allocate 2.57 GiB for an array with shape (2764800000,) and data type uint8

HI!!
When I want to use stl10 dataset error happended.....
I have changed the file like below

flags.DEFINE_enum('dataset', 'stl10', ['cifar10', 'stl10'], "dataset")
flags.DEFINE_string('fid_cache', './stats/stl10.unlabeled.48.npz', 'FID cache') 

可是它說沒有內存的樣子。。我該怎麼辦。。求指點。。
謝謝您

**Comment by w86763777** [comment]
This means the size of STL10 is larger than your memory.
You have to increase your system memory or write a custom dataloader to read the dataset on the fly.

**Comment by sumorday** [comment]
> 

Thank you so much!!!!!
