### ISSUE TITLE
What is the effect of adding uniform noise?

### ISSUE THREAD

**Issue by kevinbro96** [w86763777/pytorch-gan-collections#6]
Hi! I am wandering what is the effect of adding uniform noise?

**Comment by w86763777** [comment]
I guess your question is about line 97 and 106 in [sngan.py](https://github.com/w86763777/pytorch-gan-collections/blob/master/sngan.py#L97). I just follow the [official implementation](https://github.com/pfnet-research/sngan_projection/blob/master/datasets/cifar10.py#L19) to augment the dataset by adding uniform noise, so there is nothing special here.
Hope this information can help you.

**Comment by w86763777** [comment]
closed
