### ISSUE TITLE
How do I change to my own dataset?

### ISSUE THREAD

**Issue by leelbc** [w86763777/pytorch-gan-collections#7]

**Comment by w86763777** [comment]
Currently not support custom dataset directly. You should update code to load your own dataset. For example, update these [lines](https://github.com/w86763777/pytorch-gan-collections/blob/master/sngan.py#L91-L107).

**Comment by w86763777** [comment]
This feature will not be supported since this repository is an example project for GAN. Close the issue.

**Comment by eeeclipse** [comment]
I found the way to train custom dataset. 
Try `from torchvision.datasets import ImageFolder`
