### ISSUE TITLE
"ResNet Block Architecture" Question

### ISSUE THREAD

**Issue by Harvey-W** [w86763777/pytorch-gan-collections#9]
https://github.com/w86763777/pytorch-gan-collections/blob/2adbd7867cdbb4cec5130b26d0bf7bb1927d70e0/source/models/sngan.py#L232

Hi, I learned SNGAN (https://arxiv.org/pdf/1802.05957.pdf) with your code.
Assume that "Table 5: ResNet architectures for STL-10 dataset." is referred to the code above, I don't know why there is an "optimized block" whereas I cannot find it within all the paper.
So could you tell me what it is and where I can learn it? THX a lot!

**Comment by w86763777** [comment]
Please refer to the official sngan implementation [link](https://github.com/pfnet-research/sngan_projection/blob/master/dis_models/resblocks.py#L52).
